# Generated by Django 4.1.13 on 2023-12-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0004_musicbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicbase',
            name='co_author',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
