# Generated by Django 4.1.13 on 2023-12-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0005_musicbase_co_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=40)),
                ('co_author', models.CharField(max_length=40)),
                ('album', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_core.users')),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
