# Generated by Django 4.1.13 on 2023-12-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0006_musiclinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclinks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_links', to='users_core.users'),
        ),
        migrations.AlterModelTable(
            name='musiclinks',
            table='music_links',
        ),
    ]
