# Generated by Django 4.1.13 on 2023-12-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0007_alter_musiclinks_user_alter_musiclinks_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicLinks',
            new_name='Music_Links',
        ),
    ]
