# Generated by Django 4.1.13 on 2023-12-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_core', '0008_rename_musiclinks_music_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicbase',
            name='dop_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
